export interface FoodItem {
  name: string;
  serving: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
}

export const FOODS: FoodItem[] = [
  { name: 'Apple', serving: '1 medium', calories: 95, protein: 0.5, carbs: 25, fat: 0.3 },
  { name: 'Banana', serving: '1 medium', calories: 105, protein: 1.3, carbs: 27, fat: 0.4 },
  { name: 'Orange', serving: '1 medium', calories: 62, protein: 1.2, carbs: 15, fat: 0.2 },
  { name: 'Strawberries', serving: '1 cup', calories: 49, protein: 1, carbs: 12, fat: 0.5 },
  { name: 'Blueberries', serving: '1 cup', calories: 84, protein: 1.1, carbs: 21, fat: 0.5 },
  { name: 'Grapes', serving: '1 cup', calories: 104, protein: 1.1, carbs: 27, fat: 0.2 },
  { name: 'Watermelon', serving: '1 cup', calories: 46, protein: 0.9, carbs: 12, fat: 0.2 },
  { name: 'Avocado', serving: '1/2 fruit', calories: 120, protein: 1.5, carbs: 6, fat: 11 },
  { name: 'Carrot', serving: '1 medium', calories: 25, protein: 0.6, carbs: 6, fat: 0.1 },
  { name: 'Broccoli', serving: '1 cup cooked', calories: 55, protein: 3.7, carbs: 11, fat: 0.6 },
  { name: 'Spinach', serving: '1 cup cooked', calories: 41, protein: 5.3, carbs: 7, fat: 0.5 },
  { name: 'Tomato', serving: '1 medium', calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2 },
  { name: 'Cucumber', serving: '1 cup sliced', calories: 16, protein: 0.7, carbs: 3.8, fat: 0.1 },
  { name: 'Sweet potato', serving: '1 medium', calories: 103, protein: 2.3, carbs: 24, fat: 0.2 },
  { name: 'Potato (boiled)', serving: '1 medium', calories: 145, protein: 3, carbs: 34, fat: 0.2 },
  { name: 'White rice', serving: '1 cup cooked', calories: 205, protein: 4.3, carbs: 45, fat: 0.4 },
  { name: 'Brown rice', serving: '1 cup cooked', calories: 216, protein: 5, carbs: 45, fat: 1.8 },
  { name: 'Oatmeal', serving: '1 cup cooked', calories: 154, protein: 6, carbs: 27, fat: 3 },
  { name: 'Granola', serving: '1/2 cup', calories: 210, protein: 5, carbs: 33, fat: 8 },
  { name: 'Whole wheat bread', serving: '1 slice', calories: 81, protein: 4, carbs: 14, fat: 1.1 },
  { name: 'White bread', serving: '1 slice', calories: 79, protein: 2.7, carbs: 15, fat: 1 },
  { name: 'Bagel', serving: '1 medium', calories: 289, protein: 11, carbs: 56, fat: 1.7 },
  { name: 'Pasta', serving: '1 cup cooked', calories: 221, protein: 8, carbs: 43, fat: 1.3 },
  { name: 'Tortilla (flour)', serving: '1 medium', calories: 144, protein: 4, carbs: 24, fat: 3.5 },
  { name: 'Croissant', serving: '1 medium', calories: 272, protein: 5.5, carbs: 31, fat: 14 },
  { name: 'Muffin (blueberry)', serving: '1 medium', calories: 313, protein: 4.5, carbs: 49, fat: 11 },
  { name: 'Pancakes', serving: '2 medium', calories: 175, protein: 5, carbs: 28, fat: 5 },
  { name: 'French toast', serving: '2 slices', calories: 300, protein: 9, carbs: 35, fat: 14 },
  { name: 'Egg (boiled)', serving: '1 large', calories: 78, protein: 6.3, carbs: 0.6, fat: 5.3 },
  { name: 'Egg (fried)', serving: '1 large', calories: 92, protein: 6.3, carbs: 0.4, fat: 7 },
  { name: 'Scrambled eggs', serving: '2 eggs', calories: 182, protein: 12, carbs: 2, fat: 14 },
  { name: 'Omelette (cheese)', serving: '2 eggs', calories: 280, protein: 17, carbs: 2, fat: 22 },
  { name: 'Bacon', serving: '2 slices', calories: 92, protein: 6, carbs: 0.3, fat: 7 },
  { name: 'Sausage', serving: '1 link', calories: 190, protein: 9, carbs: 2, fat: 16 },
  { name: 'Ham', serving: '2 slices', calories: 92, protein: 13, carbs: 2, fat: 3.5 },
  { name: 'Turkey breast', serving: '100 g', calories: 135, protein: 30, carbs: 0, fat: 1 },
  { name: 'Chicken breast', serving: '150 g', calories: 247, protein: 46, carbs: 0, fat: 5.4 },
  { name: 'Chicken thigh', serving: '150 g', calories: 315, protein: 37, carbs: 0, fat: 18 },
  { name: 'Grilled chicken', serving: '1 piece', calories: 284, protein: 44, carbs: 0, fat: 11 },
  { name: 'Beef steak', serving: '150 g', calories: 357, protein: 39, carbs: 0, fat: 21 },
  { name: 'Ground beef', serving: '100 g cooked', calories: 250, protein: 26, carbs: 0, fat: 16 },
  { name: 'Pork chop', serving: '150 g', calories: 315, protein: 38, carbs: 0, fat: 17 },
  { name: 'Lamb chop', serving: '2 chops', calories: 355, protein: 35, carbs: 0, fat: 23 },
  { name: 'Salmon', serving: '150 g', calories: 312, protein: 34, carbs: 0, fat: 19 },
  { name: 'Tuna (canned)', serving: '1 can', calories: 132, protein: 29, carbs: 0, fat: 1 },
  { name: 'Cod', serving: '150 g', calories: 123, protein: 27, carbs: 0, fat: 1 },
  { name: 'Shrimp', serving: '150 g', calories: 148, protein: 30, carbs: 2, fat: 2 },
  { name: 'Tofu', serving: '150 g', calories: 114, protein: 12, carbs: 3, fat: 7 },
  { name: 'Lentils', serving: '1 cup cooked', calories: 230, protein: 18, carbs: 40, fat: 0.8 },
  { name: 'Chickpeas', serving: '1 cup cooked', calories: 269, protein: 15, carbs: 45, fat: 4 },
  { name: 'Black beans', serving: '1 cup cooked', calories: 227, protein: 15, carbs: 41, fat: 0.9 },
  { name: 'Hummus', serving: '1/4 cup', calories: 145, protein: 4, carbs: 10, fat: 11 },
  { name: 'Peanut butter', serving: '2 tbsp', calories: 188, protein: 8, carbs: 6.3, fat: 16 },
  { name: 'Almonds', serving: '1 oz (23)', calories: 164, protein: 6, carbs: 6.1, fat: 14 },
  { name: 'Walnuts', serving: '1 oz', calories: 185, protein: 4.3, carbs: 3.9, fat: 18 },
  { name: 'Cashews', serving: '1 oz', calories: 157, protein: 5.2, carbs: 8.6, fat: 12 },
  { name: 'Mixed nuts', serving: '1 oz', calories: 173, protein: 5, carbs: 6, fat: 15 },
  { name: 'Milk (whole)', serving: '1 cup', calories: 149, protein: 7.7, carbs: 12, fat: 8 },
  { name: 'Milk (skim)', serving: '1 cup', calories: 83, protein: 8.3, carbs: 12, fat: 0.2 },
  { name: 'Greek yogurt', serving: '1 cup', calories: 130, protein: 23, carbs: 9, fat: 1.5 },
  { name: 'Yogurt (plain)', serving: '1 cup', calories: 149, protein: 8.5, carbs: 11, fat: 8 },
  { name: 'Cheese (cheddar)', serving: '1 oz', calories: 115, protein: 6.5, carbs: 0.9, fat: 9.5 },
  { name: 'Mozzarella', serving: '1 oz', calories: 85, protein: 6.3, carbs: 0.6, fat: 6.3 },
  { name: 'Cottage cheese', serving: '1/2 cup', calories: 92, protein: 12, carbs: 4, fat: 3 },
  { name: 'Protein shake', serving: '1 scoop', calories: 130, protein: 24, carbs: 4, fat: 2 },
  { name: 'Butter', serving: '1 tbsp', calories: 102, protein: 0.1, carbs: 0, fat: 11.5 },
  { name: 'Olive oil', serving: '1 tbsp', calories: 119, protein: 0, carbs: 0, fat: 13.5 },
  { name: 'Cheddar & crackers', serving: '1 snack box', calories: 310, protein: 9, carbs: 30, fat: 18 },
  { name: 'Pizza (cheese)', serving: '1 slice', calories: 285, protein: 12, carbs: 36, fat: 10 },
  { name: 'Pizza (pepperoni)', serving: '1 slice', calories: 313, protein: 13, carbs: 36, fat: 13 },
  { name: 'Hamburger', serving: '1 burger', calories: 354, protein: 21, carbs: 30, fat: 17 },
  { name: 'Cheeseburger', serving: '1 burger', calories: 402, protein: 24, carbs: 31, fat: 21 },
  { name: 'Hot dog', serving: '1 with bun', calories: 314, protein: 11, carbs: 25, fat: 19 },
  { name: 'Chicken sandwich', serving: '1 sandwich', calories: 440, protein: 27, carbs: 41, fat: 19 },
  { name: 'Burrito (chicken)', serving: '1 burrito', calories: 610, protein: 33, carbs: 62, fat: 26 },
  { name: 'Tacos (beef)', serving: '2 tacos', calories: 340, protein: 19, carbs: 30, fat: 16 },
  { name: 'Quesadilla', serving: '1 quesadilla', calories: 430, protein: 21, carbs: 36, fat: 22 },
  { name: 'Sushi roll (california)', serving: '6 pieces', calories: 255, protein: 9, carbs: 38, fat: 7 },
  { name: 'Sushi roll (salmon)', serving: '6 pieces', calories: 290, protein: 15, carbs: 38, fat: 8 },
  { name: 'Ramen', serving: '1 bowl', calories: 550, protein: 18, carbs: 70, fat: 21 },
  { name: 'Fried rice', serving: '1 cup', calories: 330, protein: 7, carbs: 45, fat: 13 },
  { name: 'Chicken curry', serving: '1 bowl', calories: 460, protein: 32, carbs: 30, fat: 24 },
  { name: 'Chili con carne', serving: '1 bowl', calories: 330, protein: 24, carbs: 26, fat: 14 },
  { name: 'Tomato soup', serving: '1 bowl', calories: 170, protein: 5, carbs: 28, fat: 5 },
  { name: 'Chicken noodle soup', serving: '1 bowl', calories: 200, protein: 14, carbs: 24, fat: 6 },
  { name: 'Green salad', serving: '1 bowl', calories: 90, protein: 3, carbs: 10, fat: 4 },
  { name: 'Caesar salad', serving: '1 bowl', calories: 320, protein: 12, carbs: 15, fat: 24 },
  { name: 'Chicken Caesar salad', serving: '1 bowl', calories: 450, protein: 35, carbs: 18, fat: 26 },
  { name: 'French fries', serving: 'medium', calories: 365, protein: 4, carbs: 48, fat: 17 },
  { name: 'Onion rings', serving: '6 rings', calories: 310, protein: 4, carbs: 36, fat: 17 },
  { name: 'Coleslaw', serving: '1/2 cup', calories: 145, protein: 1, carbs: 9, fat: 12 },
  { name: 'Chips (potato)', serving: '1 oz bag', calories: 152, protein: 2, carbs: 15, fat: 10 },
  { name: 'Popcorn', serving: '3 cups', calories: 165, protein: 5, carbs: 19, fat: 8 },
  { name: 'Pretzels', serving: '1 oz', calories: 108, protein: 2.6, carbs: 23, fat: 0.8 },
  { name: 'Cookies (chocolate chip)', serving: '2 cookies', calories: 240, protein: 3, carbs: 33, fat: 12 },
  { name: 'Chocolate bar (milk)', serving: '1 bar', calories: 235, protein: 3.4, carbs: 26, fat: 13 },
  { name: 'Dark chocolate', serving: '1 oz', calories: 170, protein: 2.2, carbs: 13, fat: 12 },
  { name: 'Ice cream', serving: '1/2 cup', calories: 137, protein: 2.3, carbs: 16, fat: 7.3 },
  { name: 'Cheesecake', serving: '1 slice', calories: 350, protein: 6, carbs: 30, fat: 23 },
  { name: 'Brownie', serving: '1 piece', calories: 280, protein: 3.4, carbs: 36, fat: 14 },
  { name: 'Donut', serving: '1 glazed', calories: 269, protein: 4, carbs: 31, fat: 15 },
  { name: 'Cinnamon roll', serving: '1 medium', calories: 320, protein: 6, carbs: 50, fat: 11 },
  { name: 'Honey', serving: '1 tbsp', calories: 64, protein: 0.1, carbs: 17, fat: 0 },
  { name: 'Ketchup', serving: '1 tbsp', calories: 17, protein: 0.2, carbs: 4.5, fat: 0 },
  { name: 'Mayonnaise', serving: '1 tbsp', calories: 94, protein: 0.1, carbs: 0.1, fat: 10 },
  { name: 'Ranch dressing', serving: '2 tbsp', calories: 129, protein: 0.6, carbs: 1.8, fat: 13 },
  { name: 'Salsa', serving: '2 tbsp', calories: 10, protein: 0.4, carbs: 2.2, fat: 0 },
  { name: 'Coffee (black)', serving: '1 cup', calories: 2, protein: 0.3, carbs: 0, fat: 0 },
  { name: 'Latte', serving: '12 oz', calories: 150, protein: 8, carbs: 14, fat: 7 },
  { name: 'Cappuccino', serving: '12 oz', calories: 110, protein: 6, carbs: 9, fat: 6 },
  { name: 'Orange juice', serving: '1 cup', calories: 112, protein: 1.7, carbs: 26, fat: 0.5 },
  { name: 'Coca-Cola', serving: '1 can', calories: 139, protein: 0, carbs: 39, fat: 0 },
  { name: 'Beer', serving: '12 oz', calories: 153, protein: 1.6, carbs: 13, fat: 0 },
  { name: 'Red wine', serving: '5 oz', calories: 125, protein: 0.1, carbs: 3.8, fat: 0 },
];

const FOOD_NAMES_LC: string[] = FOODS.map((f) => f.name.toLowerCase());

export function searchFoods(query: string, limit = 30): FoodItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return FOODS.slice(0, 12);
  const starts: FoodItem[] = [];
  const contains: FoodItem[] = [];
  for (let i = 0; i < FOODS.length; i++) {
    if (FOOD_NAMES_LC[i]!.startsWith(q)) starts.push(FOODS[i]!);
    else if (FOOD_NAMES_LC[i]!.includes(q)) contains.push(FOODS[i]!);
  }
  return [...starts, ...contains].slice(0, limit);
}
